### ISSUE TITLE
Does this tool support link time optimization?

### ISSUE THREAD

**Issue by z472421519** [pangine/disasm-eval-sources#1]
Hello, I use this tools to generate ground truth of coreutils-8.2.5 download by git clone. I used -flto option, but the program crashed. The run.sh is as followed:
```bash
#!/bin/bash

source ${LINUX_SCRIPTS_DIR}/run_prefix.sh

mkdir build
cd ${HOME}/${PKG}/build
${LINUX_SCRIPTS_DIR}/git_prepare.sh
../configure --prefix=${HOME}/local CFLAGS="${OPTIONS} -flto --save-temps -g -Wno-error"
${LINUX_SCRIPTS_DIR}/git_prepare.sh
make install
${LINUX_SCRIPTS_DIR}/git_finish.sh

# Move files to result directories
mv ${HOME}/local/bin/* ${BIN_DIR}/${PKG}
cd ${HOME}/${PKG}
mv build ${BUILD_DIR}/${PKG}

source ${LINUX_SCRIPTS_DIR}/run_suffix.sh
```
And the log is 
>
        Matching lst and obj file: mkdir.ltrans0.lst <-> mkdir.ltrans0.o
                close_stream:   ERROR: function does not exist in obj: "close_stream"
        ----------discard----------

**Comment by Cryspia** [comment]
Currently the tool does not support link time optimization. We cannot found the source listing files for the optimized code at link time, thus the tool cannot match the correct ground truth in a binary.
